### ISSUE TITLE
Unable to grant optional permissions to RES

### ISSUE THREAD

**Issue by LarsBauer** [honestbleeps/Reddit-Enhancement-Suite#5185] opened 2020-03-17 12:08 UTC
- My browser: Vivalid 2.12.1849.7 (Official Build) (64-bit)
- My RES version: 5.18.11
- Am I in reddit beta (yes/no): no

*What's the problem?*
I am unable to grant optional permissions to RES. When I open an expando, I get the RES permissions required dialog, but nothing else happens. The Request Permissions toggle in RES settings to grant all permissions at once is greyed-out (see related /r/RESissues threads).

I checked `background.entry.js` and found the following error in the developer console:

```
Unchecked runtime.lastError: This function must be called during a user gesture
```

I investigated further and could narrow it down to the following function, especially the contains request:

```javascript
addListener('permissions', handleMessage);
    function handleMessage({operation, permissions, origins}) {
        switch (operation) {
        case 'contains':
            // this request fails with given error message
            return apiToPromise(chrome.permissions.contains)({
                permissions,
                origins
            });

        case 'request':
            return apiToPromise(chrome.permissions.request)({
                permissions,
                origins
            }).catch(e=>{
                console.error(e);
                return false;
            }
            );

        default:
            throw new Error(`Invalid permissions operation: ${operation}`);
        }
    }
```
This seems to be a Chromium-specific behaviour as Firefox is working fine. Maybe it is related to Chromium 81, which is the foundation for the given Vivaldi version.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
 - https://www.reddit.com/r/RESissues/comments/fgf3vy/cant_grant_expando_permissions_in_vivaldi/
- https://www.reddit.com/r/RESissues/comments/fcvbvc/google_drive_etc_backup_and_restore_permission/

*What other browser extensions are installed?*
- Enpass extension
- JSON Viewer
- Privacy Badger
- uBlock Origin

**Comment by BenMcGarry** [comment] 2020-03-18 20:36
Non Repo on Chrome/Edge/Opera releases based on Chromium 81.

Repo on Vivaldi 2.12.1854.5 (Official Build) (64-bit) based on Chrome/81.0.4044.66. Appears to be Vivaldi specific.

**Comment by BenMcGarry** [comment] 2020-03-20 10:11
Bug confirmed with Vivaldi.

> Hi,
> 
> Thank you for reporting the issue.
> This issue has been confirmed and passed to the team for further process. 
> 
> We’re a small team so please bear in mind that (depending on the complexity) it may take a while for the fix to get into our Stable version. 
> 
> Thank you for reporting and using Vivaldi.

**Comment by LarsBauer** [comment] 2020-03-20 11:22
Thank you for raising this issue and the quick feedback.
Can you provide me the VB number, so I can keep an eye open in the Vivaldi changelog?

**Comment by BenMcGarry** [comment] 2020-03-20 11:24
VB-64791 is what they are tracking it on.

**Comment by BenMcGarry** [comment] 2020-03-20 11:56
If you see it fixed, can you let us know so we can update on our end?

**Comment by LarsBauer** [comment] 2020-03-20 13:14
I will definitely do that!

**Comment by creesch** [comment] 2020-06-24 07:46
I just noticed that it now works in vivaldi due to the same fallback firefox uses, thanks to [this commit](https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/6faae61fb5193ae49d3ba91f4c0f04d4aa974534). So while it isn't fixed in vivaldi at least it works now for RES.

**Comment by LarsBauer** [comment] 2020-06-24 16:09
Thank you guys for providing this workaround. Makes RES usable on Vivaldi again 🙌 

By the way I asked for progress on VB-64791 a couple of days ago and unfortunately they made no progress so far. I would suggest it is up to you guys whether to keep this issue alive until it is fixed for real.

**Comment by BenMcGarry** [comment] 2020-06-24 16:11
We'll close this as we are keeping the fall back method for all browsers. Glad Vivaldi is usable!

**Closed by BenMcGarry** 2020-06-24 16:11 UTC
Labels: Priority-0_Externally Blocked
