### ISSUE TITLE
White Box in place of Standard Reddit Favicon

### ISSUE THREAD

**Issue by draggehn** [honestbleeps/Reddit-Enhancement-Suite#4486] opened 2017-10-21 21:32 UTC
- My browser: Firefox 58 Nightly on Windows 10
- My RES version: 5.8.6
- Am I in reddit beta (yes/no): Yes

*What's the problem?*

On every page where RES is active, the favicon is a white box. See below reddit post (submitted by me) for all troubleshooting steps I have gone through, but I am fairly certain it is a problem with RES: I disabled every single addon aside from RES, and the white favicon issue persisted. After disabling RES, however, the issue disappeared and I was able to see the favicon in all of its glory once more.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

Yes, one that I submitted: https://www.reddit.com/r/RESissues/comments/77hu6k/white_box_in_place_of_favicon/

*What other browser extensions are installed?*

Screenshot here: https://i.imgur.com/AJ4FFEL.png

**Comment by BenMcGarry** [comment] 2017-10-21 23:15
https://www.reddit.com/r/RESissues/comments/77hu6k/white_box_in_place_of_favicon/doly77r/

**Comment by erikdesjardins** [comment] 2017-10-22 22:13
I can't reproduce, which nightly revision are you using? (also works without new messages)

![image](https://user-images.githubusercontent.com/7673145/31866892-eab3ac02-b753-11e7-96fa-4cd855f64f28.png)

Have you tried disabling all extensions except RES? If it's a conflict between two extensions, disabling them one-by-one will implicate the first one you happen to turn off.

Do you have something that could be messing with canvas elements (i.e. for antifingerprinting)?

That doesn't turn anything up, try [creating a second Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and see if it still happens.

**Comment by BenMcGarry** [comment] 2017-10-22 22:26
Possibly related: https://bugzilla.mozilla.org/show_bug.cgi?id=1403963

**Comment by draggehn** [comment] 2017-10-23 23:48
@erikdesjardins It is indeed because I had "privacy.resistFingerprinting" enabled. Toggling that setting off reveals the lovely Snoo that I missed. Do you know of any way to have this setting enabled and still have the favicon show up?

**Comment by erikdesjardins** [comment] 2017-10-24 01:56
If you disable [showUnreadCountInFavicon](https://reddit.com/#res:settings/orangered/showUnreadCountInFavicon), RES should stop replacing the favicon.

Closing as there's not much we can feasibly do here; checking if the canvas is white would be (relatively) difficult as it's generated inside favico.js, few users have antifingerprinting enabled, and the workaround is easy.

**Closed by erikdesjardins** 2017-10-24 01:56 UTC
