### ISSUE TITLE
Expando permission prompts do not appear when 1Password is installed on Chromium

### ISSUE THREAD

**Issue by imagebird** [honestbleeps/Reddit-Enhancement-Suite#5531] opened 2024-08-07 07:29 UTC
- My browser (copy from https://www.whatismybrowser.com): Chrome 127 on Windows 19
- My RES version: v5.24.6
- Am I in reddit beta (yes/no): no

*What's the problem?*

When expanding embeds, permission prompts do not appear when 1Password's extension is enabled.

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://old.reddit.com/r/RESissues/comments/1eeeo76/cant_grant_expando_permissions_in_chromium_browser/

*What other browser extensions are installed?*

![image](https://github.com/user-attachments/assets/61ae3cc9-60fb-4fad-8a55-77a00c5855e8)

**Comment by yyli** [comment] 2024-08-10 13:49
I can confirm that I have the same issue. If I disable 1password the expando permission prompt shows up.

**Comment by benmcgarry** [comment] 2024-08-21 22:52
This appears to be a 1PW issues, i've reached out to them.

**Comment by jef** [comment] 2024-08-28 02:50
Just confirmed this information as well. Thanks for reaching out to them @benmcgarry; hopefully we'll get an update!

**Comment by benmcgarry** [comment] 2024-08-31 23:24
As an update to this, 1Password have confirmed its an issue on their side. However they have given no timeframe for it to be fixed or any commitment that it will be fixed. 

Will keep this open to track with whatever happens. Going to see about adding a dialog to detect 1PW and throwing an alert telling them to temporarily disable it for RES to work fully.

**Comment by ncla** [comment] 2024-09-16 09:07
Do you know if there is a way to track this issue on 1Password side (forum, issue tracker etc.)?

My team are developing our own browser extension and experienced permissions pop-ups not appearing after calling [browser.permissions.request](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request). I am MacOS and Brave myself, and I use 1Password browser extension as well, and after disabling 1Password extension, the permissions pop-ups appeared after _user click_.

A workaround I found is if you can navigate to the button that triggers the permission request with just keyboard, by pressing TAB and SPACE button, you can trigger the browser permission modal that way.

It's strange that this is caused by 1Password, but reading the WebExtension docs I am thinking this is something to do with what browser considers an [user action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).

**Comment by benmcgarry** [comment] 2024-09-16 09:14
> Do you know if there is a way to track this issue on 1Password side (forum, issue tracker etc.)?
> 
> 
> 
> My team are developing our own browser extension and experienced permissions pop-ups not appearing after calling [browser.permissions.request](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request). I am MacOS and Brave myself, and I use 1Password browser extension as well, and after disabling 1Password extension, the permissions pop-ups appeared after _user click in page context_.
> 
> 
> 
> A workaround I found is if you can navigate to the button that triggers the permission request with just keyboard, by pressing TAB and SPACE button, you can trigger the browser permission modal that way.
> 
> 
> 
> It's strange that this is caused by 1Password, but reading the WebExtension docs I am thinking this is something to do with what browser considers an [user action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).

Nothing they shared with me, honestly I don't think their devs are even looking into it. Best option is probably raising more support tickets telling them it's a problem.

**Closed** 2024-09-21 19:45 UTC
Labels: Priority-8_Important
