### ISSUE TITLE
Can't reinstall RES on Firefox

### ISSUE THREAD

**Issue by SnowGabe** [honestbleeps/Reddit-Enhancement-Suite#2209] opened 2015-04-29 14:47 UTC
I had to reinstall RES because removing Bitdefender Wallet "browser hijacker" broke the extension. Unfortunately I only backup to cloud using symbolic links and restoring an earlier version wasn't possible.
Now RES doesn't work and I only see what probably is "vanilla Reddit". I've removed the folder "jid1-xUfzOsOFlzSOXg@jetpack" and the location will always be recreated when I reinstall RES.
I want to know that is "<profile folder>/jetpack/jid1-xUfzOsOFlzSOXg@jetpack" the location of RES folder (and created by Reddit Enhancement Suite) or something that Firefox requires to function?

I've never had any issues before. I used 'RogueKiller' antivirus application to remove Bitdefender Wallet extension because nothing else worked.

**Comment by allthefoxes** [comment] 2015-04-29 15:25
Its far better to report these things on /r/resissues - At least until it can be pinned down to an issue with the RES code. Your issue is probably something with firefox or your computer.

I have heard that the issue is that the browser hijacker changes your permissions. Restoring your computer to a backup should fix everything.

**Comment by SnowGabe** [comment] 2015-04-29 17:34
Bitdefender Wallet isn't malicious of course, the extension is just installed without my permission.

**Comment by allthefoxes** [comment] 2015-04-29 18:06
If nothing works to remove it except an anti virus, thats pretty malicious

**Comment by mc10** [comment] 2015-05-14 10:01
Closing this as there isn't any direct bug related to RES code, but feel free to make a submission to [r/RESissues](https://www.reddit.com/r/RESissues).

**Closed by mc10** 2015-05-14 10:01 UTC
Labels: Browser-Firefox
