### ISSUE TITLE
Multireddit navigation popup disappears before you can hover over it

### ISSUE THREAD

**Issue by Farow** [honestbleeps/Reddit-Enhancement-Suite#3494] opened 2016-09-30 18:30 UTC
Repro steps:
- visit a multi
- hover over the currently selected multi
- move mouse towards popup

This could be a Firefox only issue, @andytuba mentioned on irc:

> <andytuba> but in chrome it works fine for me if i move my mouse directly from the tab onto the menu

Browser: Firefox 49.0.1 x64, RES: 5.0.2.

**Comment by dhensche** [comment] 2016-11-16 18:41
okay, think I figured this out. Each time a `mouseover` event is occurring for the `li` a call to the following is being made
```javascript
target(element) {
	if (typeof element !== 'undefined') {
		this.close();
		this._target = element;
	}

	return this;
}
```
Once the popup is visible this is causing it to close without using the fade option so it closes immediately. There is a small gap between the li element and where the menu pops up for the currently selected multi, which is why this is happening. If you move your mouse fast enough you don't see the issue. I've replicated it in chrome 54.0.2840.71 and FF 50.0

**Comment by dhensche** [comment] 2016-11-16 19:06
looks like the issue is in the `_startShowTimer()` function:

```javascript
_startShowTimer() {
	this.mouseEvent = 'enter';

	if (this.visible && this.mouseEvent === 'enter') {
		// Close and reopen container.
		this._cancelShow();
	}
	this._cancelShowTimer();
	this.showTimer = setTimeout(::this._afterShowTimer, this._options.openDelay);
}
```
For the selected multi, there is a gap between the bounding box of the li element that the mouseover event is attached to and the popup. If you move your mouse too slowly the above function is executed which immediately closes the popup and queues it be reopened in the openDelay (default of 1s). We could either override the style on the selected multi (reddit applys a `margin-right: -8px; padding-right: 8px`) to be 0 all around so there is no gap or have the above method maybe set the timeout to 0 if it is already visible (effectively closing and reopening the popup immediately).

**Comment by Express50** [comment] 2017-07-22 15:10
I'd like to take a crack at this. If I go the overriding css route, should I do it in the main css file or do I need to create a separate module?

**Closed** 2017-09-17 03:07 UTC
Labels: Difficulty-­2_Medium, Priority-2_A litte more Interest
