### ISSUE TITLE
Extended Subreddit Search Form

### ISSUE THREAD

**Issue by blindman** [honestbleeps/Reddit-Enhancement-Suite#2714] opened 2016-02-09 02:40 UTC
Just a simple enhancement that I couldn't find a dupe through my searches.

When using the subreddit search page, it might be useful for some people to have a form to fill out for the refined search section that will automatically fill in the search box with the values in the form so they don't have to worry about the syntax.  I failed horrendously at making a mock-up, sorry.

Here is the section I'm referencing:

<img width="1058" alt="" src="http://i.imgur.com/YrEQ1ak.png">

**Comment by erikdesjardins** [comment] 2016-02-09 03:53
Related to / possibly duplicates #1160

**Comment by blindman** [comment] 2016-02-09 04:14
@erikdesjardins Yepp, def related.

**Comment by erikdesjardins** [comment] 2016-09-10 21:45
Closing as duplicate of #1160, I guess I forgot to.

**Closed by erikdesjardins** 2016-09-10 21:45 UTC
