### ISSUE TITLE
J at bottom of posts page doesn't go to next page

### ISSUE THREAD

**Issue by Sorgrum** [honestbleeps/Reddit-Enhancement-Suite#4549] opened 2017-11-16 23:47 UTC
- My browser (copy from https://www.whatismybrowser.com): Firefox Develop Edition 57 on Windows 10
- My RES version: 5.8.6
- Am I in reddit beta (yes/no): no

*What's the problem?*
When navigating posts, the J key will normally advance to the next page. It doesn't anymore

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
No

*What other browser extensions are installed?*
1Password
uBlock Origin
Multi-Account Containers

**Comment by erikdesjardins** [comment] 2017-11-17 05:20
Duplicate of #4328

**Closed by erikdesjardins** 2017-11-17 05:20 UTC

**Comment by erikdesjardins** [comment] 2017-11-17 19:33
If you have NER disabled, then pressing J should never navigate to the next page. It did at one point, but that was due a bug in 5.6.2.

You can press N to navigate to the next page; you'll have to press G first if useGoMode is enabled (which it is by default).
