### ISSUE TITLE
Gallery does not convert gif to gifv

### ISSUE THREAD

**Issue by fbm-static** [honestbleeps/Reddit-Enhancement-Suite#2199] opened 2015-04-24 09:46 UTC
When an imgur gallery is linked, the contents are displayed as images. However, when one of them/all of them is/are gif(s) they don't get converted to gifv.

Thanks.

**Comment by andytuba** [comment] 2015-04-24 21:35
duplicate of #1833. working on it this week too!

**Closed by andytuba** 2015-04-24 21:35 UTC

**Comment by fbm-static** [comment] 2015-04-25 23:22
Aw, sorry I didn't notice man. Cheers!
