### ISSUE TITLE
subredditStyleBrowserToolbarButton shows on all websites although disabled

### ISSUE THREAD

**Issue by girst** [honestbleeps/Reddit-Enhancement-Suite#4535] opened 2017-11-09 08:57 UTC
- My browser: Firefox Developer Edition 58.0b1
- My RES version: 5.8.6
- Am I in reddit beta (yes/no): no

*What's the problem?*

the "toggle subreddit style" button on the address bar is shown on every website (not just reddit.com), even though it is disabled in RES settings (subredditStyleBrowserToolbarButton -> off). 
It can be removed by right-clicking it and selecting "remove from address bar", but reappears after a browser restart

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://www.reddit.com/r/RESissues/comments/7ai3ir/subreddit_style_browser_toolbar_button_always/

*What other browser extensions are installed?*

- canvasblocker
- decentraleyes
- ghostery
- https everywhere
- javascript toggle on and off (webextension)
- passff
- reddit enhancement suite
- ublock origin
- vimfx
- violentmonkey

**Comment by erikdesjardins** [comment] 2017-11-09 19:28
Duplicate of #4262

**Closed by erikdesjardins** 2017-11-09 19:28 UTC
