### ISSUE TITLE
When going to put a title in a post, the character has a red "x/null" text

### ISSUE THREAD

**Issue by JMccormick264** [honestbleeps/Reddit-Enhancement-Suite#4561] opened 2017-11-26 16:12 UTC
- My browser:
   - Firefox 59 on Windows 10
   -  Firefox Nightly Build
- My RES version: 
    -  5.9.1 (also latest github commits)
- Am I in reddit beta (yes/no): 
    - Yes

*What's the problem?*
Whenever i go to post, the title always has in red x/null on the right. The "x" always increased the number as I type. Shown here: https://puu.sh/ytWAY/f7b94380f9.png

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
[Reddit Issue post Here](https://www.reddit.com/r/RESissues/comments/6iwkza/letter_count_for_title_in_posts_shows_xnull_when/)
[Issue Post here](https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/4502)

*What other browser extensions are installed?*
Reddit Moderator Toolbox
Ad Block Plus
LastPass Password Manager

**Comment by erikdesjardins** [comment] 2017-11-26 23:46
Duplicate of #4502

**Closed by erikdesjardins** 2017-11-26 23:46 UTC
