### ISSUE TITLE
video expando issue - exception with example

### ISSUE THREAD

**Issue by honestbleeps** [honestbleeps/Reddit-Enhancement-Suite#1987] opened 2015-01-19 02:17 UTC
https://www.reddit.com/r/RESissues/comments/2svx5m/bug_inline_video_expando_sometimes_throws/

**Comment by erikdesjardins** [comment] 2015-01-19 03:00
[Here's the post they linked to](https://www.reddit.com/r/funny/comments/2stti1/boop/), I can't reproduce on Chrome 39, 42, nor Firefox 35 (on Windows).

It appears that the templates don't get loaded in time, so `templateElements` is undefined on [this line](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5ed21ca62742647f150f9a866d0063217536f008/lib/core/template.js#L60) (per the error).

**Comment by jsayol** [comment] 2015-08-30 07:31
I couldn't reproduce it either but the likely culprit seems to be the quickMessage module. It's the only place where [the templates are accessed synchronously](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5ed21ca62742647f150f9a866d0063217536f008/lib/modules/quickMessage.js#L33) (calling RESTemplates.getSync() instead of RESTemplates.load() with callback). In some fringe cases the templates might not be loaded yet when this module initializes.

**Comment by erikdesjardins** [comment] 2016-05-11 18:13
Closing as `templates.js` is dead (we now import `.mustache` files directly).

**Closed by erikdesjardins** 2016-05-11 18:13 UTC
Labels: Priority-8_Important, RE-Bug-Confirmed
